### ISSUE TITLE
 Cannot use module 'ShadowImageView' as a type

### ISSUE THREAD

**Issue by Jinkeycode** [olddonkey/ShadowImageView#10]
![image](https://user-images.githubusercontent.com/12148377/28050709-f05d750c-6631-11e7-9978-85abc4b3dc06.png)
纯代码引入的时候报这个错误，版本1.5.0

**Comment by olddonkey** [comment]
我今天晚上看看，奇怪的是为什么github不邮件我提醒有issue.
另外问一下这个在什么用法下出现的？看起来像是名字重复？不应该呀。。。

**Comment by ApolloZhu** [comment]
权限不够，现在是 framework 的 internal，要在[这里](https://github.com/olddonkey/ShadowImageView/blob/master/Sources/ShadowImageView.swift#L13) 加上 `public`
```swift
public class ShadowImageView: UIView {
```

**Comment by olddonkey** [comment]
@ApolloZhu 谢谢指出 👍 ，我们WWDC的时候应该见过？
@Jinkeycode 已更新，请查看是否解决

**Comment by Jinkeycode** [comment]
已更新，正常了
