### ISSUE TITLE
求大神改进

### ISSUE THREAD

**Issue by vitaminbat** [olddonkey/ShadowImageView#5]
大神能把blurredImageView去掉吗，感觉浪费内存。。

**Comment by olddonkey** [comment]
您好，感谢您的反馈。
不是很明白为什么要去掉blurredImageView？

**Comment by vitaminbat** [comment]
不好意思，没说清楚。
我是想说，如果把blurredImage和originImage都渲染到一张画布上，能省掉blurredImageView这部分的初始化开销和后续一直存在的内存开销。这样会不会更好？

**Comment by olddonkey** [comment]
确实是个节约内存的办法，我现在之所以这样做事因为我准备之后加动画，所以在最开始开发的时候就没有考虑用CALayer，不过确实是个值得考虑的东西。

谢谢反馈。：）

**Comment by vitaminbat** [comment]
不客气，期待下一个版本。^_^
