### ISSUE TITLE
'-[CIContext initWithOptions:]: unrecognized selector sent to instance 0x789cdac0'

### ISSUE THREAD

**Issue by Jinkeycode** [olddonkey/ShadowImageView#6]
generateBlurBackground() -> applyBlur() -> let context = CIContext(options: nil)

Can you fix this problem in iOS 8.2 ?

**Comment by olddonkey** [comment]
It is a bug in iOS8 when compiler transfer the method into OC, there are some workaround with that, I will try some ways to fix this

**Comment by olddonkey** [comment]
你好，我merge了你的change, 但是你的project setting有点问题，所以我重新设置了一下，现在应该可以了，顺便改了一下category的名字，更宽泛一点，另外加了travis ci支持。

如果有什么问题，欢迎随时reopen这个issue

**Comment by Jinkeycode** [comment]
上次提交这个问题是因为我和朋友业余时间开发的一个小工具（优读）使用了你的开源框架遇到的，顺便修复了 ，现在 app 已经发布，可否在自述文件加上我们的案例 ？

**名称**：优读

**简介**：一站式订阅、收藏、碎片化知识管理平台，可以订阅公众号、简书等各大平台信息源；基于职业的高效过滤和推荐算法为你提供个性化信息流，让你的学习更专注；优质文章极速搜藏，智能归类，自动打标签，时间再也不浪费在整理上。

**下载地址**：[https://itunes.apple.com/us/app/优读-订阅收藏和碎片知识管理神器/id1175225244](https://itunes.apple.com/us/app/优读-订阅收藏和碎片知识管理神器/id1175225244)

**截图**
：![image](https://user-images.githubusercontent.com/12148377/27427787-cd6502e0-5772-11e7-9361-93462956d5f7.png)

**Comment by olddonkey** [comment]
好，我晚上更新，顺便说一下，貌似你的code是很老的code，有线程问题，会导致动画丢失，最好可以更新一下

**Comment by Jinkeycode** [comment]
我也发现了，我现在可以直接 pod update 咯？

**Comment by olddonkey** [comment]
对，直接pod更新到1.5.0就可以了。另外给点个人小建议，阴影的Alpha可以稍微低一点，不会太喧宾夺主，还有你的colloection view的cell的尺寸偏小，在有几个出现了一点点阴影边缘被截断的情况，可以改一下

**Comment by Jinkeycode** [comment]
好的，谢谢你的建议，我修改一下
