### ISSUE TITLE
iOs animations stop working

### ISSUE THREAD

**Issue by ConnorMusic** [olddonkey/ShadowImageView#9]
When I use it sometimes ios animations stop working. I revised my code but its correct. I try to do the same without your pod and works fine.
I think that it is cause you are updating the UI without using the `DispatchQueue.main.async`. Please revised and tell me something cause your project its incredible. Thanks

**Comment by olddonkey** [comment]
You are right, I forget to dispatch to main thread, I will update it today. Thanks so much for let me know

**Comment by olddonkey** [comment]
Hi, I have updated the project, using CALayer instead of UIView, please test if the problem exist or not.

Let me know if the problem is still there.

**Comment by olddonkey** [comment]
I will close this for now, if you have problem, feel free to reopen this.
